version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    image: app:django
    container_name: images_app
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres
    container_name: images_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ImagesApp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres