version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    image: app:django
    container_name: django_images
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres
    container_name: postgres_images
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}